import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth } from '../firebase';
import { signOut } from 'firebase/auth';
import { QuestionWizard } from '../components/QuestionWizard';
import { BulkUpload, QuestionExplorer, QuestionExporter } from '../components/AdminComponents';
import { Logo } from '../components/Logo';

export function AdminPage() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'wizard' | 'bulk'>('wizard');

  const handleLogout = async () => {
    await signOut(auth);
    navigate('/');
  };

  const jsonSchema = `{
  "grade": number (1-12),
  "level": number (1-10),
  "difficulty": "gifted",
  "type": "logic" | "arithmetic" | "geometry",
  "question": "string",
  "options": ["A", "B", "C", "D", "E"],
  "correct_answer": "string",
  "ideal_solution": "string",
  "failure_modes": {
    "calculation_error": "string",
    "conceptual_misunderstanding": "string"
  }
}`;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-4 sm:px-8 py-3 sm:py-4 flex justify-between items-center flex-wrap gap-y-2">
        <div className="flex items-center space-x-2 sm:space-x-4">
          <Logo className="h-6 sm:h-8 w-auto" />
          <h1 className="text-lg sm:text-2xl font-bold text-gray-900 tracking-tight">Admin Dashboard</h1>
          <span className="hidden sm:inline px-2 py-1 bg-red-50 text-red-600 text-[10px] font-black uppercase tracking-widest rounded-md border border-red-100">
            Authenticated
          </span>
        </div>
        <div className="flex items-center space-x-3 sm:space-x-4">
          <button 
            onClick={() => navigate('/')}
            className="text-xs sm:text-sm font-bold text-gray-400 hover:text-gray-900 transition-colors uppercase tracking-widest"
          >
            Site Home
          </button>
          <button 
            onClick={handleLogout}
            className="px-3 sm:px-4 py-1.5 sm:py-2 bg-gray-900 text-white rounded-lg text-xs sm:text-sm font-bold hover:bg-black transition-all"
          >
            Logout
          </button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden">
        {/* Sidebar / Documentation */}
        <aside className="w-80 bg-white border-r border-gray-200 p-6 overflow-y-auto hidden lg:block flex flex-col space-y-8">
          <div>
            <h2 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Question Schema</h2>
            <pre className="bg-gray-900 text-green-400 p-4 rounded-xl text-[10px] font-mono leading-relaxed overflow-x-auto border border-gray-800 shadow-inner">
              {jsonSchema}
            </pre>
          </div>

          <QuestionExporter />

          <div className="space-y-4">
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400">Instructions</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Use the **Wizard** for manual, high-quality entries with live validation.
            </p>
            <p className="text-xs text-gray-500 leading-relaxed">
              Use **Bulk Upload** to paste JSON arrays generated by LLMs or external tools.
            </p>
          </div>
        </aside>

        {/* Main Content */}
        <main className="flex-1 overflow-y-auto p-8">
          <div className="max-w-4xl mx-auto space-y-8">
            {/* Tabs */}
            <div className="flex space-x-1 bg-gray-200 p-1 rounded-xl w-fit">
              <button
                onClick={() => setActiveTab('wizard')}
                className={`px-6 py-2 rounded-lg text-sm font-bold transition-all ${
                  activeTab === 'wizard' ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                Question Wizard
              </button>
              <button
                onClick={() => setActiveTab('bulk')}
                className={`px-6 py-2 rounded-lg text-sm font-bold transition-all ${
                  activeTab === 'bulk' ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                Bulk JSON Upload
              </button>
            </div>

            {/* Tab Panels */}
            <div className="bg-white rounded-3xl border border-gray-200 shadow-sm p-8 min-h-[600px]">
              {activeTab === 'wizard' ? (
                <QuestionWizard />
              ) : (
                <BulkUpload />
              )}
            </div>

            {/* Question List / Explorer */}
            <QuestionExplorer />
          </div>
        </main>
      </div>
    </div>
  );
}
